apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-kate.fullname" . }}
  labels:
    app: hello-kate-frontend
    release: {{ .Release.Name }}
    version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: hello-kate-frontend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: hello-kate-frontend
        release: {{ .Release.Name }}
        version: {{ .Chart.AppVersion }}
    spec:
      securityContext:
        runAsUser: {{ .Values.runAsUser }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: hello-kate-frontend
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.container.image.repository }}:{{ .Values.deployment.container.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.deployment.container.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.deployment.container.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            {{- if .Values.ingress.enabled }}
            path: {{ .Values.routing.basepath | trimSuffix "/" }}/health
            {{- else }}
            path: /health
            {{- end }}
            port: {{ .Values.deployment.container.port }}
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            {{- if .Values.ingress.enabled }}
            path: {{ .Values.routing.basepath | trimSuffix "/" }}/health
            {{- else }}
            path: /health
            {{- end }}
            port: {{ .Values.deployment.container.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        env:
        - name: basepath
        {{- if .Values.ingress.enabled }}
          value: {{ .Values.routing.basepath }}
        {{- else }}
          value: null
        {{- end }}
        - name: tracing
        {{- if .Values.monitoring.tracing }}
          value: "true"
        {{- else }}
          value: "false"
        {{- end }}
        - name: mongodb
          value: {{ .Release.Name }}-mongodb
        - name: mongodb_user
          value: {{ .Values.mongodb.mongodbUsername }}
        - name: mongodb_password
          value: {{ .Values.mongodb.mongodbPassword }}
        - name: HELLO_MESSAGE
          value: {{ .Values.message | default "Hello Kubernetes!" }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
