apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-kate.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-kate-frontend
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }} # ClusterWide Port
      targetPort: {{ .Values.deployment.container.port }} # In Pod