apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-kate.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: hello-kate-frontend
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 80 # ClusterWide Port
      targetPort: 8080 # In Pod