{{- if .Values.ingress.istio.virtualservice.deploy }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "hello-kate.fullname" . }}
spec:
  hosts:
  {{- toYaml .Values.ingress.istio.virtualservice.hosts | nindent 2 }}
  gateways:
  - {{ .Values.ingress.istio.virtualservice.gateway }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.routing.basepath }}
    route:
    - destination:
        host: {{ include "hello-kate.fullname" . }}
{{- end }}