# -----------------------
#  Service Configuration
# -----------------------
service:
  type: LoadBalancer # Set to ClusterIP if using Ingress
  externalPort: 80

# -----------------------------------
#  Ingress and Routing Configuration
# -----------------------------------
routing:
  basepath: &basepath /hello-kate

ingress:
  enabled: false
  istio:
    gateway:
      deploy: false
      servers:
      - port:
          number: 80
          name: http
          protocol: HTTP
        hosts:
        - '*'
    virtualservice:
      deploy: false

# ------------
#  Deployment
# ------------
deployment:
  replicaCount: 2
  container:
    image:
      repository: "cmdrsharp/hello-kate"
      tag: ""
      pullPolicy: IfNotPresent
    port: 8080
  
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# --------------
#  Dependencies
# --------------
mongodb:
  mongodbUsername: testuser
  mongodbPassword: testpass
  mongodbDatabase: statistics

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 256Mi

  persistence:
    storageClass: standard-rwo
    size: 512Mi

  metrics:
    enabled: false